// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseLayout: typeof import('./src/components/common/BaseLayout.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WebPageAddDialog: typeof import('./src/components/web-page/WebPageAddDialog.vue')['default']
    WebPageContent: typeof import('./src/components/web-page/WebPageContent.vue')['default']
    WebPageContentCardItem: typeof import('./src/components/web-page/WebPageContentCardItem.vue')['default']
    WebPageContentCardItemOperation: typeof import('./src/components/web-page/WebPageContentCardItemOperation.vue')['default']
    WebPageContentCardList: typeof import('./src/components/web-page/WebPageContentCardList.vue')['default']
    WebPageContentHeader: typeof import('./src/components/web-page/WebPageContentHeader.vue')['default']
    WebPageContentOperation: typeof import('./src/components/web-page/WebPageContentOperation.vue')['default']
    WebPageDrawer: typeof import('./src/components/web-page/WebPageDrawer.vue')['default']
    WebPageDrawer1: typeof import('./src/components/web-page/WebPageDrawer1.vue')['default']
    WebPageDrawerNav: typeof import('./src/components/web-page/WebPageDrawerNav.vue')['default']
    WebPageDrawerTitle: typeof import('./src/components/web-page/WebPageDrawerTitle.vue')['default']
    WebPageSideBar: typeof import('./src/components/common/WebPageSideBar.vue')['default']
    WebPageTaskDrawer: typeof import('./src/components/web-page/WebPageTaskDrawer.vue')['default']
    WebPageWebview: typeof import('./src/components/web-page/WebPageWebview.vue')['default']
  }
}
